version: '3.8'

services:
  nginx:
    image: nginx:1.23-alpine  
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./site-content:/usr/share/nginx/html
    user: nginx
    restart: unless-stopped

  redis:
    image: redis:7.0-alpine 
    expose:
      - "6379"
    restart: unless-stopped

  php:
    image: php:8.1-fpm-alpine
    volumes:
      - ./site-content:/var/www/html
    restart: unless-stopped

  netcoreapp:
    # Utilizando una imagen distroless personalizada de .NET
    build:
      context: ./netcoreapp
      dockerfile: Dockerfile
    volumes:
      - ./netapp:/app
    working_dir: /app
    command: dotnet TestAspNetApp.dll
    restart: unless-stopped

networks:
  default:
    driver: bridge
